### PR TITLE
Update Puppet module metadata and add link to module source

### PR DESCRIPTION
**Pull request by genebean**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area integrations

**What this PR does / why we need it**:

This PR updates Puppet module metadata and adds a link to the module's source. The link added to the readme is for the benefit of people viewing https://forge.puppet.com/modules/sysdig/falco

**Which issue(s) this PR fixes**:

Relates to #142 

**Special notes for your reviewer**:

A release to the Puppet Forge will be needed to finish fixing the linked issue.

### CODE REVIEW

**Comment by genebean** [comment]
Closing as I have rewored this code into a standalone module. The current module cannot be installed via git because it is not in the root of a repo / a repo by itself.

**Comment by maxgio92** [comment]
Ok, thanks for the update @genebean

**Comment by genebean** [comment]
@maxgio92 FWIW, https://github.com/falcosecurity/falco/issues/2005 has details and https://forge.puppetlabs.com/modules/puppet/falco has been released

**Comment by maxgio92** [comment]
Thanks @genebean! I left some comments on Falco [#2005](https://github.com/falcosecurity/falco/issues/2005)

**Pull request closed without merging**
