### PR TITLE
Move org.yaml from test-infra to evolution repository

### LINKED ISSUE #176: Move `org.yaml` here
**Motivation**

It would simplify the CI and all organization-related processes which are currently initiated from this repository.

**Feature**

- move [org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml)
from `test-infra` to `evolution`.
- configure `prow` accordingly

**Alternatives**

**Additional context**
cc @falcosecurity/test-infra-maintainers

### PR DESCRIPTION
**Pull request by maxgio92**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area utils

**What this PR does / why we need it**:

As the evolution repository is now the central point for the evolution of the project, and as the falcosecurity organization is formed by the community, and as the point of contact of the contributions are in git (Github), is correct that the source of truth as a declarative configuration of the Github organization is put here.

Moreover, this PR adds the Prow job needed for the automation that reconciles the desired source of truth with the actual one.

**Which issue(s) this PR fixes**:

Fixes #176 

Supersedes #193

### CODE REVIEW

**Comment by maxgio92** [comment]
Hey @zuc @leogr, the `org.yaml` is now up to date with related history.

**Comment by leogr** [comment]
Hey @maxgio92 

Is this ready to be merged?

**Comment by maxgio92** [comment]
We need to check the history imported related to the `org.yaml` file and I think it's ready to me merged :-)

**Comment by maxgio92** [comment]
As for https://github.com/falcosecurity/test-infra/pull/841#issuecomment-1431499621, I'm going to remove the in-repo config.

Also, I"m going to update (again :-D) the `org.yaml` file, and cleanup the history.

**Comment by leogr** [comment]
This likely needs coordination with @falcosecurity/test-infra-maintainers

**Comment by maxgio92** [comment]
/close

in favor of #274

**Pull request closed without merging**
