### PR TITLE
 Move org.yaml from test-infra to evolution repository

### LINKED ISSUE #176: Move `org.yaml` here
**Motivation**

It would simplify the CI and all organization-related processes which are currently initiated from this repository.

**Feature**

- move [org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml)
from `test-infra` to `evolution`.
- configure `prow` accordingly

**Alternatives**

**Additional context**
cc @falcosecurity/test-infra-maintainers

### PR DESCRIPTION
**Pull request by maxgio92**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area utils

**What this PR does / why we need it**:

As the evolution repository is now the central point for the evolution of the project, and as the falcosecurity organization is formed by the community, and as the point of contact of the contributions are in git (Github), is correct that the source of truth as a declarative configuration of the Github organization is put here.

Moreover, this PR adds the Prow job needed for the automation that reconciles the desired source of truth with the actual one.

**Which issue(s) this PR fixes**:

Fixes #176 

Supersedes #204

/cc @leogr

### CODE REVIEW

**Comment by maxgio92** [comment]
I think we finally have a clean history @leogr.

There was history related to the source repository test-infra to a directory wrongly named "distrubution" under config.

**Comment by maxgio92** [comment]
@leogr I think we're ready to unhold this and consequently update related pipelines. WDYT?

**Comment by maxgio92** [comment]
The `org.yaml` and related history has been updated.

**Comment by maxgio92** [comment]
@falcosecurity/evolution-maintainers this is up to date and ready to be merged.

**Comment by leogr** [comment]
> @falcosecurity/evolution-maintainers is there something I can do here?

Hey @maxgio92 

I lost track of this sorry. Is anything else needed to make this work ready yet?
If yes, we should just schedule when. I would not say this is super urgent, but this issue has been open for too long, so I would address it.

@FedeDP @LucaGuerra could you help with this?

**Pull request closed without merging**
