### PR TITLE
move to falco repository

### PR DESCRIPTION
**Pull request by kaldyka**
Signed-off-by: Akos Kaldy <kaldyka@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind documentation

/kind feature

/kind sandbox

> /kind incubating

> /kind officialsupport

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area deploy

> /area examples

/area integrations

> /area proposals

**What this PR does / why we need it**:

The main purpose of this sidecar is to create an invisible connection between Falco and the Phoenix moving target defense operator (www.r6security.com). The one-way flow of information is achieved by modifying the affected Pod's annotation whenever a new Falco event occurs. Basically using  Falco events as triggers to continuously scramble the attack surface of the cluster hence making hackers' lives way harder.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by maxgio92** [comment]
Hey @kaldyka, thank you for your first contribution! We're going to review this PR ASAP :)

**Review by leodido — COMMENTED** [review]
This looks interesting!

Would someone working full-time on Falco please take a look at it, I do not have cycles rn.

@kaldyka: I've read the README, would you please add 1 or 2 lines of description to the PR corpus for future reference?

/cc @falcosecurity/evolution-maintainers

**Comment by zsmav** [comment]
@leodido something along these lines?

"The main purpose of this sidecar is to create an invisible connection between Falco and the Phoenix moving target defense operator (www.r6security.com). The one-way flow of information is achieved by modifying the affected Pod's annotation whenever a new Falco event occurs. Basically using  Falco events as triggers to continuously scramble the attack surface of the cluster hence making hackers' lives way harder."

**Comment by maxgio92** [comment]
For me that's ok @zsmav

**Comment by leodido** [comment]
> @leodido something along these lines?
> 
> "The main purpose of this sidecar is to create an invisible connection between Falco and the Phoenix moving target defense operator ([www.r6security.com](http://www.r6security.com)). The one-way flow of information is achieved by modifying the affected Pod's annotation whenever a new Falco event occurs. Basically using Falco events as triggers to continuously scramble the attack surface of the cluster hence making hackers' lives way harder."

Yup!

**Comment by zsmav** [comment]
@maxgio92 and @nestorsalceda - let us know if you need anything else. ... thanks

**Review by leogr — APPROVED** [review]

**Review by leodido — COMMENTED** [review]
💯 

/approve

**Pull request merged**
