### PR TITLE
new(docs): add LucaGuerra to OWNERS

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind documentation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area utils

**What this PR does / why we need it**:

As a core maintainer, I would like to help with the maintenance of this utility repo, as I do with .github

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
+1 for me!

**Comment by maxgio92** [comment]
+1

🥳

**Comment by jasondellaluce** [comment]
+1 ❤️

**Review by leogr — APPROVED** [review]
Since we reached the majority already
/approve

:partying_face:

**Pull request merged**
