### PR TITLE
feat(deploy): Introduce Kilt - a way to define container patches

### PR DESCRIPTION
**Pull request by admiral0**
**What type of PR is this?**

/kind feature

/kind incubating

**Any specific area of the project related to this PR?**

/area deploy

**What this PR does / why we need it**:
This PR introduces Kilt - a definition on how to include falco inside foreign containers and implementation for cloudformation. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Possible additional runtime implementations:
* k8s-build - admission controller patching pod resources based on the kilt definition
* k8s-runtime - executable performing `kubectl exec` to patch running containers
* image-patcher - patcher that produces new images that include the kilt definition

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Hey @admiral0 

thank you for this PR!

Just
/hold
until the proposal https://github.com/falcosecurity/falco/pull/1388 is approved.

Btw, may it be more convenient to create a new repo for kilt?
cc @falcosecurity/maintainers WDYT?

**Comment by maxgio92** [comment]
I, too, think Kilt itself deserves a dedicated `sandbox` repo. Instead, maybe, the way to use it to deploy Falco in userspace (i.e. in Fargate) could instead live in the `evolution` repo under `/deploy` folder (i.e. `/deploy/fargate`).

**Comment by leogr** [comment]
Hey,

we have the community call today, and I believe that's the perfect place to raise this topic.
It would be great if you'll join!

**Comment by leogr** [comment]
Closing in favor of #41
/close

**Pull request closed without merging**
