### PR TITLE
docs(REPOSITORIES.md): revising repositories "scope" and "status"

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area governance

> /area proposals

> /area utils

**What this PR does / why we need it**:

For context, see #271

This PR:

- divorces the concept of repositories _scope_ and _status_, and revise our documentation to ensure these definitions and statuses are clearly described
- as a consequence of the above point, it introduces several further changes:
   - Previously, *core* and *official* were used as synonyms. Now *core* is a scope, and *official* has been removed in favor of *stable* as a status.
   - Available **scopes** are now: _core_, _ecosystem_, _infra_, _special_ 
      - N.B. _ecosystem_ and _infra_ are new
   - Newly introduced **statuses**: _stable_, _incubating_, _sandbox_, _deprecated_ 
     - N.B. _stable_ replaced _official_, _deprecated_ is the path for archiving a repo
- introduces **clear descriptions and criteria** for statuses
- as a consequence of the above points, it also revises the status/scope of some repos, in particular
  - all repos previously defined just as "incubating" are now assigned a proper scope (_ecosystem_ or _infra_)
  - the following repositories get promoted to _stable_ since the new criteria match:
     - [falco-exporter](https://github.com/falcosecurity/falco-exporter)
     - [falcosidekick](https://github.com/falcosecurity/falcosidekick)
     - [test-infra](https://github.com/falcosecurity/test-infra)
- introduces badges for scopes and statuses
- update the automation to work with the new concepts
- as a bonus point, revise and improve all repository descriptions

**Which issue(s) this PR fixes**:

Contribute to #271 but not completely address it. 

**Special notes for your reviewer**:

This PR modifies the status or scope of some repositories to reflect the new criteria. As per our governance, this change is allowed just using lazy consensus since no core repositories have been touched. But, in case you disagree with the new categorization, just let me know.

### CODE REVIEW

**Comment by maxgio92** [comment]
Great @leogr and thank you!

/lgtm

**Comment by incertum** [comment]
@leogr 🤯 🤩 ❤️ this is truly amazing work!!! Loving it!

We could consider removing the gif from the README plus perhaps we could enhance the descriptions of the repositories to something just slightly longer / more expressive (elevator pitch like why should I care? what do I get out of this repo?) if it makes sense similar to the changes we just made to the main Falco README. On that note, we can iterate on what the perfect a bit longer description per repo should be and as a result update the Falco README and all other repos to have them all in sync -> could be combined with the PRs that add the new badges to each repo.

**Comment by leogr** [comment]
> @leogr exploding_head star_struck heart this is truly amazing work!!! Loving it!
> 
> We could consider removing the gif from the README 

[This one](https://github.com/falcosecurity/evolution/blob/main/img/pidgeotto.gif)? :crying_cat_face: 
If we agree to remove it, I'd do that in a separate PR, anyway.

> plus perhaps we could enhance the descriptions of the repositories to something just slightly longer / more expressive (elevator pitch like why should I care? what do I get out of this repo?) 

Good idea. I'll try to fix it soon. Anyway, consider we can always improve those descriptions later.

> if it makes sense similar to the changes we just made to the main Falco README. On that note, we can iterate on what the perfect a bit longer description per repo should be and as a result update the Falco README and all other repos to have them all in sync -> could be combined with the PRs that add the new badges to each repo.

Please note that GitHub will show those descriptions in the left column at the top. :point_down: I don't believe we also have to report them in each repo readme. 
Screenshot from 2023-06-01 13-06-40

**Comment by leogr** [comment]
Last update: I just revised repositories descriptions as suggested by @incertum 
Unless there're errors, I'd leave further improvements for follow-up PRs.

@falcosecurity/evolution-maintainers 
So, this PR is now ready for review 

After this PR gets merged, we can add badges to the README of all repos :star_struck: 

cc @falcosecurity/core-maintainers

**Comment by incertum** [comment]
@leogr LGTM, thank you! Agreed we can tweak the descriptions over time.

Proposing to proceed.

**Comment by maxgio92** [comment]
Looks great to me @leogr!
Thank you

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
