### PR TITLE
Add flycheck-falco-rules as an incubating project

### PR DESCRIPTION
**Pull request by mstemm**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind documentation

> /kind feature

/kind incubating

> /kind officialsupport

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area governance

/area proposals

> /area utils

**What this PR does / why we need it**:

Adding flycheck-falco-rules as an incubating project.

https://github.com/falcosecurity/evolution/issues/221 tracks the now-approved request to add the repository.

**Which issue(s) this PR fixes**:

Fixes https://github.com/falcosecurity/evolution/issues/221

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by maxgio92** [comment]
Thank you @mstemm! 🤗 
/lgtm

**Review by maxgio92 — DISMISSED** [review]
/approve

**Review by leogr — CHANGES_REQUESTED** [review]
Hey @mstemm 

The table in the README is autogenerated. IIRC, you should edit [repositories.yaml](https://github.com/falcosecurity/evolution/blob/main/repositories.yaml) instead (@jasondellaluce is that right?)

**Comment by mstemm** [comment]
Ok, updated repositories.yaml instead. And added @ewilderj to affiliations.json.

**Review by jasondellaluce — APPROVED** [review]

**Review by leogr — APPROVED** [review]

**Pull request merged**
